<a href="https://colab.research.google.com/github/KomalT2003/DiabeticFootDetection/blob/main/DiabetesDetectionANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
df = pd.read_csv("/content/Diabetes Screening (Responses) - Form Responses 1 (1).csv")

In [ ]:
# print head
df.head()

,Timestamp,Email Address,Your Age is in the range of,You identify your Gender as?,Are you working or retired,Please mention your Height (in cm),Please mention your Weight (in kg),Have you been diagnosed with Diabetes or high blood sugar (HbA1C),"Have you ever been found to have high blood glucose (e.g. in a health examination, during an illness, during pregnancy )?","Has your parent, brother, sister, or own child been diagnosed with diabetes (type 1 or type 2)?",...,what are your eating habits [Eating fried food],what are your eating habits [going out for dinners or ordering food from hotels],How physically active are you ?,Do you have any of the following symptoms,Any other problems that you would like to tell us related to your health,Unnamed: 27,Score,Images of Foot's front plane,Images of Foot's Back plane,Closeup Images of your Nail Bed
0,3/31/2024 20:36:26,anuja.jiandani@gmail.com,>=65,Male,retired,170.0,107,yes,Yes,Yes,...,once a fortnightly,once a fortnightly,walk at least 30-45 mins at my own speed daily,Blurry vision,NaN,NaN,NaN,NaN,NaN,NaN
1,3/31/2024 21:02:46,dixitnikhils@gmail.com,18-44,Male,working,164.0,77.5,No,No,Yes,...,rarely,once a month,walk at least 30-45 mins at my own speed daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3/31/2024 21:02:50,snehadixit62@gmail.com,55-64,Female,retired,150.0,67,No,No,Yes,...,rarely,rarely,walk at least 30-45 mins at my own speed daily,NaN,No,NaN,NaN,NaN,NaN,NaN
3,3/31/2024 21:44:20,NaN,55-64,Female,retired,160.0,61,yes,Yes,Yes,...,rarely,rarely,only 10-15 mins in a day,Blurry vision,No,NaN,NaN,NaN,NaN,NaN
4,3/31/2024 21:48:17,NaN,18-44,Female,working,173.0,94,No,No,Yes,...,rarely,rarely,only 10-15 mins in a day,NaN,No,NaN,NaN,NaN,NaN,NaN

In [ ]:
# state column names
df.columns

Index(['Timestamp', 'Email Address', 'Your Age is in the range of ',
       'You identify your Gender as?', 'Are you working or retired',
       'Please mention your Height (in cm)',
       'Please mention your Weight (in kg)',
       'Have you been diagnosed with Diabetes or high blood sugar (HbA1C)',
       'Have you ever been found to have high blood glucose (e.g. in a health examination, during an illness, during pregnancy )?',
       'Has your parent, brother, sister, or own child been diagnosed with diabetes (type 1 or type 2)?',
       ' Has your grandparent, aunt, uncle, or first cousin been diagnosed with diabetes (type 1 or type 2)?',
       'waist is narrowest part above the umbilicus. What is your waist circumference?',
       'Have you had health issues related to  any of the following . (Tick all that apply)',
       'Have you ever taken medication for any of the following',
       'Are you on Steroid Medication?', 'do you feel low or stressed',
       'Do you smoke ', 'How many cigarettes /bidis/ you smoke  daily ?',
       'what are your eating habits [eating vegetables]',
       'what are your eating habits [eating fruits]',
       'what are your eating habits [drinking non alcoholic beverages]',
       'what are your eating habits [drinking alcohol]',
       'what are your eating habits [Eating fried food]',
       'what are your eating habits [going out for dinners or ordering food from hotels]',
       'How physically active are you ?',
       'Do you have any of the following symptoms',
       'Any other problems that you would like to tell us related to your health',
       'Unnamed: 27', 'Score', 'Images of Foot's front plane',
       'Images of Foot's Back plane', 'Closeup Images of your Nail Bed'],
      dtype='object')

In [ ]:
# drop 1st 2 columns
df = df.drop(df.columns[[0, 1]], axis=1)

In [ ]:
# drop 27th,28th,29th,30th,31st column
df = df.drop(df.columns[[26, 27, 28, 29]], axis=1)

In [ ]:
# drop 27th,28th,29th,30th,31st column
df = df.drop(df.columns[24], axis=1)

In [ ]:
# drop unnamed columns
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [ ]:
# rename 1st column as Age
df.rename(columns={df.columns[0]: 'Age'}, inplace=True)

# rename 2nd column as Gender
df.rename(columns={df.columns[1]: 'Gender'}, inplace=True)

# rename 3rd column as Working
df.rename(columns={df.columns[2]: 'Working'}, inplace=True)

# rename 4th column as Height
df.rename(columns={df.columns[3]: 'Height'}, inplace=True)

# rename 5th column as Weight
df.rename(columns={df.columns[4]: 'Weight'}, inplace=True)

# rename 6th column as Diabetes
df.rename(columns={df.columns[5]: 'Diabetes'}, inplace=True)

# rename 7th column as Blood Sugar
df.rename(columns={df.columns[6]: 'Blood Sugar'}, inplace=True)

# rename 8th column as Close Relative
df.rename(columns={df.columns[7]: 'Close Relative'}, inplace=True)

# rename 9th column as Family History
df.rename(columns={df.columns[8]: 'Family History'}, inplace=True)

# rename 10th column as Waist Circum Range
df.rename(columns={df.columns[9]: 'Waist Circum Range'}, inplace=True)

# rename 11th column as Health Issues
df.rename(columns={df.columns[10]: 'Health Issues'}, inplace=True)

# rename 12th column as Health Condition
df.rename(columns={df.columns[11]: 'Health Condition'}, inplace=True)

# rename 13th column as Steroid
df.rename(columns={df.columns[12]: 'Steroid'}, inplace=True)

# rename 14th column as Low/Stressed
df.rename(columns={df.columns[13]: 'Low/Stressed'}, inplace=True)

# rename 15th column as Smoking
df.rename(columns={df.columns[14]: 'Smoking'}, inplace=True)

# rename 16th column as Tobacco/Smoke Range
df.rename(columns={df.columns[15]: 'Tobacco/Smoke Range'}, inplace=True)

# rename 17th column as Vegetable Frequency
df.rename(columns={df.columns[16]: 'Vegetable Frequency'}, inplace=True)

# rename 18th column as Fruit Frequency
df.rename(columns={df.columns[17]: 'Fruit Frequency'}, inplace=True)

# rename 19th column as Drinks Frequency
df.rename(columns={df.columns[18]: 'Drinks Frequency'}, inplace=True)

# rename 20th column as Alcohol Frequency
df.rename(columns={df.columns[19]: 'Alcohol Frequency'}, inplace=True)

# rename 21st column as Fried Food Frequency
df.rename(columns={df.columns[20]: 'Fried Food Frequency'}, inplace=True)

# rename 22nd column as Outside Food Frequency
df.rename(columns={df.columns[21]: 'Outside Food Frequency'}, inplace=True)

# rename 23rd column as Exercise Frequency
df.rename(columns={df.columns[22]: 'Exercise Frequency'}, inplace=True)

# rename 24th column as Diabetic Symptoms
df.rename(columns={df.columns[23]: 'Diabetic Symptoms'}, inplace=True)

In [ ]:
# For Health Issues add columns using classes
# add columns with prefix Health Issue - : Kidney Problem, Lung Problem , Muscle Weakness, Tingling Sensation, Thyroid, Paralysis, eyesight or vision, covid 19 infection, deep wound
# Blood Pressure, Heart Problem, Joint Pains, Cholestrol, Cancer, Liver Problems, Increased Body Weights

from sklearn.preprocessing import MultiLabelBinarizer

health_issues = [
    'Kidney Problem', 'Lung Problem', 'Muscle Weakness', 'Tingling Sensation', 'Thyroid', 'Paralysis',
    'Eyesight or Vision', 'COVID-19 Infection', 'Deep Wound', 'Blood Pressure', 'Heart Problem',
    'Joint Pains', 'Cholestrol', 'Cancer', 'Liver Problems', 'Increased Body Weights'
]

# Replace NaN with empty lists
df['Health Issues'] = df['Health Issues'].apply(lambda x: x if isinstance(x, list) else [])

# Initialize MultiLabelBinarizer with the specified health issues
mlb = MultiLabelBinarizer(classes=health_issues)

# Fit and transform the Health Issues column
encoded_health_issues = mlb.fit_transform(df['Health Issues'])

# Convert to DataFrame and add prefix
encoded_df = pd.DataFrame(encoded_health_issues, columns=[f'Health Issue - {issue}' for issue in mlb.classes_])

# Concatenate the original DataFrame with the encoded one
df = pd.concat([df, encoded_df], axis=1)

In [ ]:


from sklearn.preprocessing import MultiLabelBinarizer

health_conditions = [
    'blood pressure', 'blood sugar', 'cholestrol', 'heart problem', 'thyroid problem'
]

df['Health Condition'] = df['Health Condition'].apply(lambda x: x if isinstance(x, list) else [])

mlb = MultiLabelBinarizer(classes=health_conditions)

encoded_health_conditions = mlb.fit_transform(df['Health Condition'])

encoded_df = pd.DataFrame(encoded_health_conditions, columns=[f'Health Condition - {issue}' for issue in mlb.classes_])

df = pd.concat([df, encoded_df], axis=1)

In [ ]:
df

,Age,Gender,Working,Height,Weight,Diabetes,Blood Sugar,Close Relative,Family History,Waist Circum Range,...,Health Issue - Joint Pains,Health Issue - Cholestrol,Health Issue - Cancer,Health Issue - Liver Problems,Health Issue - Increased Body Weights,Health Condition - blood pressure,Health Condition - blood sugar,Health Condition - cholestrol,Health Condition - heart problem,Health Condition - thyroid problem
0,>=65,Male,retired,170.0,107,yes,Yes,Yes,No,greater than 102 cm (40 inches),...,0,0,0,0,0,0,0,0,0,0
1,18-44,Male,working,164.0,77.5,No,No,Yes,Yes,80 - 88 cm ( 35-36 inches),...,0,0,0,0,0,0,0,0,0,0
2,55-64,Female,retired,150.0,67,No,No,Yes,No,94 - 102 cm (37- 40 inches),...,0,0,0,0,0,0,0,0,0,0
3,55-64,Female,retired,160.0,61,yes,Yes,Yes,No,94 - 102 cm (37- 40 inches),...,0,0,0,0,0,0,0,0,0,0
4,18-44,Female,working,173.0,94,No,No,Yes,Yes,94 - 102 cm (37- 40 inches),...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,18-44,Female,Working,140.0,45,No,No,No,No,less than 80 am ( <31 inches),...,0,0,0,0,0,0,0,0,0,0
270,55-64,Female,Working,157.0,65,yes,Yes,Yes,Yes,94 - 102 cm (37- 40 inches),...,0,0,0,0,0,0,0,0,0,0
271,>=65,Female,Working,160.0,53,yes,Yes,Yes,No,80 - 88 cm ( 31-34 inches),...,0,0,0,0,0,0,0,0,0,0
272,>=65,Male,Retired,162.0,75,yes,No,Yes,No,greater than 102 cm (40 inches),...,0,0,0,0,0,0,0,0,0,0
273,18-44,Female,Student,172.0,90,No,No,Yes,Yes,94 - 102 cm (37- 40 inches),...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 45 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Age                                    274 non-null    object
 1   Gender                                 274 non-null    object
 2   Working                                271 non-null    object
 3   Height                                 274 non-null    float64
 4   Weight                                 274 non-null    object
 5   Diabetes                               274 non-null    object
 6   Blood Sugar                            274 non-null    object
 7   Close Relative                         274 non-null    object
 8   Family History                         272 non-null    object
 9   Waist Circum Range                     265 non-null    object
 10  Health Issues                          274 non-null    object
 11  Health Condition                       274 non-null    object
 12  Steroid                                271 non-null    object
 13  Low/Stressed                           274 non-null    object
 14  Smoking                                273 non-null    object
 15  Tobacco/Smoke Range                    78 non-null     object
 16  Vegetable Frequency                    274 non-null    object
 17  Fruit Frequency                        274 non-null    object
 18  Drinks Frequency                       274 non-null    object
 19  Alcohol Frequency                      274 non-null    object
 20  Fried Food Frequency                   274 non-null    object
 21  Outside Food Frequency                 274 non-null    object
 22  Exercise Frequency                     274 non-null    object
 23  Diabetic Symptoms                      241 non-null    object
 24  Health Issue - Kidney Problem          274 non-null    int64
 25  Health Issue - Lung Problem            274 non-null    int64
 26  Health Issue - Muscle Weakness         274 non-null    int64
 27  Health Issue - Tingling Sensation      274 non-null    int64
 28  Health Issue - Thyroid                 274 non-null    int64
 29  Health Issue - Paralysis               274 non-null    int64
 30  Health Issue - Eyesight or Vision      274 non-null    int64
 31  Health Issue - COVID-19 Infection      274 non-null    int64
 32  Health Issue - Deep Wound              274 non-null    int64
 33  Health Issue - Blood Pressure          274 non-null    int64
 34  Health Issue - Heart Problem           274 non-null    int64
 35  Health Issue - Joint Pains             274 non-null    int64
 36  Health Issue - Cholestrol              274 non-null    int64
 37  Health Issue - Cancer                  274 non-null    int64
 38  Health Issue - Liver Problems          274 non-null    int64
 39  Health Issue - Increased Body Weights  274 non-null    int64
 40  Health Condition - blood pressure      274 non-null    int64
 41  Health Condition - blood sugar         274 non-null    int64
 42  Health Condition - cholestrol          274 non-null    int64
 43  Health Condition - heart problem       274 non-null    int64
 44  Health Condition - thyroid problem     274 non-null    int64
dtypes: float64(1), int64(21), object(23)
memory usage: 96.5+ KB

In [ ]:
# Handling age column
# Encode date ranges 18-44 as 1, 45-54 as 2, 55-64 as 3, >=65 as 4
df['Age'] = df['Age'].replace(['18-44', '45-54', '55-64', '>=65'], [1, 2, 3, 4])

In [ ]:
# Handling Gender column
# Encode Male as 1 and Female as 0 other as 2
df['Gender'] = df['Gender'].replace(['Male', 'Female', 'other'], [1, 0, 2])

In [ ]:
# Handling Working Column
# Encode Student as 0, Working as 1, Retired as 2
df['Working'] = df['Working'].replace(['Student', 'Working', 'Retired'], [0, 1, 2])
df['Working'] = df['Working'].replace(['student', 'working', 'retired'], [0, 1, 2])

# Drop rows with NaN in Working column
df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=['Working'])

# Convert Working column to integer
df['Working'] = df['Working'].astype(int)

In [ ]:
# Handling Height Column

# print all values in height column
print(df['Height'].unique())

# convert to int by rounding off
df['Height'] = df['Height'].astype(int)

[170.    164.    150.    160.    173.    149.    165.    167.    171.
  72.    175.    163.    158.    172.    153.    152.    187.    185.
 162.56  155.    180.    152.4    12.9     5.6   157.    162.    176.
 154.    194.    169.    147.    179.    161.5   164.6   156.    168.
 159.    162.5   151.    148.    155.448 145.      1.    177.    154.94
 146.    167.64  158.49  164.59  161.54  161.    170.6   143.    164.5
 167.6   144.    177.8   172.7   178.    175.26  183.    190.    121.
 140.   ]

In [ ]:
# Handling Weight Column
# remove kg and kgs from data
df['Weight'] = df['Weight'].str.replace('kg', '')
df['Weight'] = df['Weight'].str.replace('kgs', '')
df['Weight'] = df['Weight'].str.replace('Kg', '')
df['Weight'] = df['Weight'].str.replace('s', '')
df['Weight'] = df['Weight'].str.replace(' ', '')


# print all values in weight column
print(df['Weight'].unique())

# convert to float type
df['Weight'] = df['Weight'].astype(float)

# print all values in weight column
print(df['Weight'].unique())

['107' '77.5' '67' '61' '94' '53' '110' '72' '63' '75' '69' '85' '71' '90'
 '80' '68' '47' '83' '64' '105' '74' '58' '70' '54' '50' '59' '86' '51'
 '42' '56' '45' '62' '48' '81' '77' '60' '84' '65' '79' '57' '55' '82'
 '44' '40' '52' '60.5' '89' '96' '58.5' '97' '73' '49' '46' '66' '76'
 '160' '71.4' '88.71' '81.5' '58.8' '83.5' '69.95' '115' '43.1' '57.9'
 '47.9' '89.7' '98.6' '87' '43' '92']
[107.    77.5   67.    61.    94.    53.   110.    72.    63.    75.
  69.    85.    71.    90.    80.    68.    47.    83.    64.   105.
  74.    58.    70.    54.    50.    59.    86.    51.    42.    56.
  45.    62.    48.    81.    77.    60.    84.    65.    79.    57.
  55.    82.    44.    40.    52.    60.5   89.    96.    58.5   97.
  73.    49.    46.    66.    76.   160.    71.4   88.71  81.5   58.8
  83.5   69.95 115.    43.1   57.9   47.9   89.7   98.6   87.    43.
  92.  ]

In [ ]:
# Handling Diabetes column
# Encode Yes as 1 and No as 0
df['Diabetes'] = df['Diabetes'].replace(['Yes', 'No'], [1, 0])

In [ ]:
# Handling Blood Sugar column
# Encode Yes as 1 and No as 0
df['Blood Sugar'] = df['Blood Sugar'].replace(['Yes', 'No'], [1, 0])

In [ ]:
# Handling Close Relative column
# Encode Yes as 1 and No as 0
df['Close Relative'] = df['Close Relative'].replace(['Yes', 'No'], [1, 0])

# Handling Family History column
# Encode Yes as 1 and No as 0
df['Family History'] = df['Family History'].replace(['Yes', 'No'], [1, 0])

In [ ]:
# Handling Waist Circum Range
print(df['Waist Circum Range'].unique())

# encode less than 80 am ( <31 inches) as 1
# encode 80 - 88 cm ( 31-34 inches) as 2
# encode 89 - 93 cm (35-36 inches) as 3
# encode 94 - 102 cm (37- 40 inches) as 4
# encode greater than 102 cm (40 inches) as 5
df['Waist Circum Range'] = df['Waist Circum Range'].replace(['less than 80 am ( <31 inches)', '80 - 88 cm ( 35-36 inches)','89 - 93 cm (35-36 inches)', '94 - 102 cm (37- 40 inches)', 'greater than 102 cm (40 inches)'], [1, 2, 3, 4, 5])

['greater than 102 cm (40 inches)' '80 - 88 cm ( 35-36 inches)'
 '94 - 102 cm (37- 40 inches)' 'less than 80 am ( 31 inches)'
 '89 - 93 cm (35 -36 inches)' nan 'less than 80 am ( <31 inches)'
 '80 - 88 cm ( 31-34 inches)' '89 - 93 cm (35-36 inches)']

In [ ]:
print(df['Waist Circum Range'].unique())

[5 2 4 'less than 80 am ( 31 inches)' '89 - 93 cm (35 -36 inches)' nan 1
 '80 - 88 cm ( 31-34 inches)' 3]

In [ ]:
# Handling Health Issues
# print unique values
print(df['Health Issues'].unique())

# Create columns named all these unique values inside the array
df = pd.concat([df, df['Health Issues'].str.get_dummies(sep=', ')], axis=1)

TypeError: unhashable type: 'list'

In [ ]:
# Handle steroid column
# Encode Yes as 1 and No as 0
df['Steroid'] = df['Steroid'].replace(['Yes', 'No'], [1, 0])

# drop records with values null
df = df.dropna(subset=['Steroid'])

# convert steroid column to int
df['Steroid'] = df['Steroid'].astype(int)

<ipython-input-160-6f64999f0830>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Steroid'] = df['Steroid'].astype(int)

In [ ]:
# Handle Low/Stressed column
# Encode never as 0, rarely as 1, often as 2, most of the time as 3, everyday as 4
df['Low/Stressed'] = df['Low/Stressed'].replace(['never', 'rarely', 'often', 'most of the time', 'everyday'], [0, 1, 2, 3, 4])

<ipython-input-131-7864910f4ecf>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Low/Stressed'] = df['Low/Stressed'].replace(['never', 'rarely', 'often', 'most of the time', 'everyday'], [0, 1, 2, 3, 4])

In [ ]:
# Handle Smoking column
# encode no as 0, yes as 2, was smoking earlier stopped for more than six months as 1
df['Smoking'] = df['Smoking'].replace(['no', 'yes', 'was smoking earlier stopped for more than six months'], [0, 2, 1])